alter table hotels add column location varchar(255) not null default 'Pending location';

create table drivers (
    available boolean not null,
    id bigint generated by default as identity,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    dni varchar(255) not null unique,
    email varchar(255) not null unique,
    license_number varchar(255) not null unique,
    phone varchar(255),
    primary key (id)
);

create table buses (
    available_seats integer not null,
    total_seats integer not null,
    driver_id bigint not null,
    id bigint generated by default as identity,
    plate_number varchar(255) not null unique,
    primary key (id)
);

alter table buses add constraint FK_buses_driver foreign key (driver_id) references drivers;
